### ISSUE TITLE
Multiple Connections of Existing Peer Created - On 'Connect' button is clicked multiple times

### ISSUE THREAD

**Issue by ditml** [jahnavi23-web/gmeet_clone#5]
**Bug:** When the same PeerID is supplied to connect, _multiple data connections_ are being created unnecessarily on each click.
**Fix:** Check if the supplied PeerID is present on the existing connections and Create a new connection only iff there are no existing connection with that particular PeerID. 
![Gmeet_bug](https://user-images.githubusercontent.com/82939848/179157343-42326c54-06f1-4527-8f1f-0294fc78094a.png)

**Comment by jahnavi23-web** [comment]
![Gmeet_bug_fixed](https://user-images.githubusercontent.com/85470384/179174391-ec0a8af5-c46f-4f77-a8ca-9cb2ad0a2098.png)
